# Generated by Django 4.2.4 on 2023-08-26 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a product feature (e.g. Fan Kitchen-cabinet wardropes)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a product feature (e.g. Swimming-pool CCTV Solar-power)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(help_text='Enter a brief description of the project', max_length=1000)),
                ('location', models.CharField(max_length=300)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('hectares', models.DecimalField(blank=True, decimal_places=1, help_text='Enter the number of hectares', max_digits=6, null=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('status', models.CharField(blank=True, choices=[('Not started', 'Not started'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed')], default='Not started', help_text='Project work status', max_length=50)),
                ('purpose', models.CharField(blank=True, choices=[('Residential', 'Residential'), ('Commercial', 'Commercial'), ('Others', 'Others')], default='Residential', help_text='Project purpose', max_length=50)),
                ('facilities', models.ManyToManyField(help_text='Select a feature for this project', to='estates.projectfacility')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('title_document', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('specification', models.CharField(help_text='Enter a brief specification of the product', max_length=300)),
                ('location', models.CharField(help_text='Enter a the product location', max_length=300)),
                ('bedrooms', models.PositiveIntegerField(blank=True, null=True)),
                ('bathrooms', models.PositiveIntegerField(blank=True, null=True)),
                ('payment_duration', models.PositiveIntegerField(help_text='Enter a number in months e.g 18')),
                ('available_units', models.PositiveIntegerField(blank=True, null=True)),
                ('outright_payment', models.DecimalField(decimal_places=2, default=0, help_text='Enter the outright payment price', max_digits=12)),
                ('mortgage_payment', models.DecimalField(decimal_places=2, default=0, help_text='Enter the mortgage payment price', max_digits=12)),
                ('installmental_payment', models.DecimalField(decimal_places=2, default=0, help_text='Enter installmental payment price', max_digits=12)),
                ('floor_area', models.PositiveBigIntegerField(help_text='Enter the net floor area for the product')),
                ('image', models.ImageField(upload_to='images/')),
                ('sales', models.CharField(blank=True, choices=[('Sold Out', 'Sold Out'), ('Now Selling', 'Now Selling'), ('On Request', 'On Request'), ('Not Available', 'Not Available')], default='Now Selling', help_text='Product sales status', max_length=50)),
                ('type', models.CharField(blank=True, choices=[('Land', 'Land'), ('Building', 'Building')], default='Building', help_text='Product type status', max_length=50)),
                ('features', models.ManyToManyField(help_text='Select a feature for this product', to='estates.feature')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='estates.project')),
            ],
        ),
        migrations.CreateModel(
            name='HouseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_name', models.CharField(blank=True, max_length=250, null=True)),
                ('house_specification', models.CharField(help_text='Enter a brief specification of the product', max_length=300)),
                ('house_floor_area', models.PositiveBigIntegerField(help_text='Enter the net floor area for the product')),
                ('units', models.PositiveIntegerField(blank=True, null=True)),
                ('house_outright_payment', models.DecimalField(decimal_places=2, default=0, help_text='Enter the outright payment price', max_digits=12)),
                ('image', models.ImageField(default=True, upload_to='images/')),
                ('bed', models.PositiveIntegerField(default=1, help_text='Enter the number of bedroom')),
                ('bath', models.PositiveIntegerField(default=1, help_text='Enter the Number of bathroom')),
                ('status', models.CharField(blank=True, choices=[('For Rent', 'For Rent'), ('For Sale', 'For Sale')], default='For Sale', help_text='House Type Status', max_length=50)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='housetypes', to='estates.project')),
            ],
        ),
    ]
